apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:                          # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: mssql                     # name of the Kubernetes Secret object
    type: Opaque
    data: 
    - objectName: "mssql-secret"           # name of the mounted content to sync. This could be the object name or object alias 
      key: mssql                           # data field to populate. This must match in deployment yaml for key
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<clientidhere"
    keyvaultName: "jrkeyvaultdemo"               # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: mssql-secret
          objectType: secret       # object types: secret, key or cert
    tenantId: "<tenantidhere>" # the tenant ID of the KeyVault